links:
  link1: "http://www.michaelhartl.com/"
  link2: "http://www.railstutorial.org/"
  links: "http://news.railstutorial.org/"
  link3: "http://www.railstutorial.org/contact"
  link4: "http://www.railstutorial.org/"
  link5: "http://www.railstutorial.org/book"
  link6: "http://screencasts.railstutorial.org/"
  link7: "http://rubyonrails.org/"
  link8: "http://www.railstutorial.org/help"
numbers:
  maximum_50: 50
  maximum_255: 255
  minimum_6: 6
  size_80: 80
